// Generated by CoffeeScript 1.9.3
(function() {
  var techAnimation;

  $(function() {
    var $container, $doc, $techAnim;
    $techAnim = $('.tech-anim');
    if ($techAnim.length > 0) {
      $doc = $(document);
      window.techAnim = new techAnimation();
      $container = $('.slides');
      return $container.fullpage({
        verticalCentered: false,
        css3: true,
        navigation: true,
        navigationPosition: 'left',
        navigationTooltips: ['', 'Infrastructure', 'Gateway', 'Load Balancing', 'Application', 'Bastion', 'Database', 'Scaling'],
        showActiveTooltip: true,
        afterLoad: function(anchorLink, index) {
          return techAnim.play[index - 1].call(this);
        },
        onLeave: function(index, nextIndex, direction) {
          if (direction === 'down') {
            return techAnim.leave[index - 1].call(this);
          } else {
            return techAnim.leaveUp[index - 2].call(this);
          }
        },
        afterRender: function() {
          return $container.css('opacity', 1);
        }
      });
    }
  });

  techAnimation = (function() {
    var animState, infrastructure, intro, leaveApp, leaveBastion, leaveDatabase, leaveGateway, leaveInfrastructure, leaveIntro, leaveNetwork, leaveScaling, leaveUpGateway, leaveUpInfrastructure, network, playApp, playBastion, playDatabase, playGateway, playInfrastructure, playIntro, playNetwork, playScaling;

    function techAnimation() {}

    network = null;

    animState = {
      console: false,
      http: false,
      load_balancer: false,
      app: false,
      ssh: false,
      bastion: false,
      database: false
    };

    intro = {
      play: false,
      end: false
    };

    infrastructure = {
      play: false
    };

    playIntro = function() {
      animate({
        el: '.console',
        easing: 'easeOutCirc',
        opacity: [0, 1],
        translateY: [1000, 0],
        duration: 1500,
        delay: 100
      });
      if (!intro.play) {
        animate({
          el: '.intro-header',
          easing: 'easeOutCirc',
          opacity: [0, 1],
          duration: 1500,
          delay: 1600
        });
        animate({
          el: '.intro-text',
          easing: 'easeOutQuad',
          opacity: [0, 1],
          duration: 1500,
          delay: 1900
        });
        animate({
          el: '.primary-header',
          easing: 'easeOutQuad',
          opacity: [0, 1],
          duration: 1000,
          delay: 2300
        });
        return setTimeout((function() {
          var $src;
          intro.play = true;
          $src = $('.b1-text');
          return Helpers.typeConsole('aptible apps:create test-app', $src);
        }), 2000);
      }
    };

    playInfrastructure = function() {
      if (!infrastructure.play) {
        $.fn.fullpage.setAllowScrolling(false);
        animate({
          el: '.fixed-panel',
          easing: 'easeOutQuad',
          opacity: [0, 1],
          translateY: [80, 0],
          duration: 300,
          delay: 600
        });
        animate({
          el: '#infrastructure .copy',
          easing: 'easeOutQuad',
          opacity: [0, 1],
          duration: 800
        });
        animate({
          el: '.customer-vpc-dots',
          opacity: [0, 1],
          scaleX: [0.8, 1.0],
          scaleY: [0.8, 1.0],
          duration: 1200,
          delay: 1300
        });
        animate({
          el: '.loading-circle-1',
          opacity: [0, 1],
          scaleX: [0.8, 1.0],
          scaleY: [0.8, 1.0],
          duration: 1200,
          delay: 1400,
          complete: function(obj) {
            return $(obj).addClass('rotate-rev');
          }
        });
        animate({
          el: '.loading-circle-2',
          opacity: [0, 1],
          scaleX: [0.8, 1.0],
          scaleY: [0.8, 1.0],
          duration: 1200,
          delay: 1500,
          complete: function(obj) {
            return $(obj).addClass('rotate');
          }
        });
        animate({
          el: '.loading-text',
          easing: 'easeOutCirc',
          opacity: [0, 1],
          translateY: [10, 0],
          duration: 600,
          delay: 2000
        });
        setTimeout((function() {
          $('.loading-circle-1, .loading-circle-2, .loading-text').fadeOut();
          return $('.customer-vpc-dots, .customer-vpc').addClass('loaded');
        }), 3000);
        setTimeout((function() {
          return $('.aws span.title, aws span.title').css('color', 'rgba(255,255,255,0.1)');
        }), 3600);
        animate({
          el: '.private',
          opacity: [0, 1],
          easing: 'easeOutCirc',
          duration: 400,
          delay: 4000
        });
        setTimeout((function() {
          return $('.private').addClass('loaded');
        }), 4200);
        animate({
          el: '.public span',
          opacity: [0, 1],
          translateY: [10, 0],
          duration: 1000,
          delay: 5400
        });
        animate({
          el: '.private span',
          opacity: [0, 1],
          translateY: [10, 0],
          duration: 1000,
          delay: 5700
        });
        animate({
          el: '.public .left, .public .right',
          easing: 'easeOutCirc',
          opacity: [0, 1],
          duration: 800,
          delay: 6500
        });
        animate({
          el: '.load-balancer, .app, .bastion, .database',
          easing: 'easeOutCirc',
          opacity: [0, 1],
          duration: 1200,
          delay: 7100
        });
        return setTimeout((function() {
          $.fn.fullpage.setAllowScrolling(true);
          return infrastructure.play = true;
        }), 7000);
      }
    };

    playGateway = function() {
      $('.http, .ssh').addClass('faded');
      setTimeout((function() {
        return $('.docker').addClass('faded');
      }), 100);
      network = new Network();
      network.generateNetwork();
      return network.generateLines();
    };

    playNetwork = function() {
      return $('.http, .load-balancer').removeClass('faded');
    };

    playApp = function() {
      return $('.app').removeClass('faded');
    };

    playBastion = function() {
      return $('.ssh, .bastion').removeClass('faded');
    };

    playDatabase = function() {
      return $('.database').removeClass('faded');
    };

    playScaling = function() {
      $('.load-balancer, .app, .bastion').removeClass('faded');
      return setTimeout((function() {
        return network.runHalf2();
      }), 3000);
    };

    techAnimation.prototype.stopIntro = function() {
      return animate.stop('.console');
    };

    leaveIntro = function() {
      return animate({
        el: '.console',
        easing: 'easeOutQuad',
        translateY: [0, 50],
        opacity: [1, 0],
        duration: 400
      });
    };

    leaveInfrastructure = function() {
      return $('#infrastructure .copy').fadeOut(100);
    };

    leaveGateway = function() {
      $('#gateway .copy').fadeOut(100);
      return network.runHttp();
    };

    leaveNetwork = function() {
      $('#network .copy').fadeOut(100);
      $('.http, .load-balancer').addClass('faded');
      return network.stop();
    };

    leaveApp = function() {
      $('#code .copy').fadeOut(100);
      $('.app').addClass('faded');
      return network.runSSH();
    };

    leaveBastion = function() {
      $('#bastion .copy').fadeOut(100);
      $('.bastion').addClass('faded');
      $('.ssh').addClass('faded');
      return network.stop();
    };

    leaveDatabase = function() {
      $('#database .copy').fadeOut(100);
      return network.runHalf();
    };

    leaveScaling = function() {};

    leaveUpInfrastructure = function() {
      return animate({
        el: ".fixed-panel",
        easing: "easeOutQuad",
        opacity: [1, 0],
        duration: 300
      });
    };

    leaveUpGateway = function() {
      return $('.http, .ssh, .load-balancer, .app, .bastion, .database').removeClass('faded');
    };

    techAnimation.prototype.play = [playIntro, playInfrastructure, playGateway, playNetwork, playApp, playBastion, playDatabase, playScaling];

    techAnimation.prototype.leave = [leaveIntro, leaveInfrastructure, leaveGateway, leaveNetwork, leaveApp, leaveBastion, leaveDatabase, leaveScaling];

    techAnimation.prototype.leaveUp = [leaveUpInfrastructure, leaveUpGateway];

    return techAnimation;

  })();

}).call(this);
