// Generated by CoffeeScript 1.9.3
(function() {
  var techAnimation;

  $(function() {
    var $container, $doc, $techAnim;
    $techAnim = $('.tech-anim');
    if ($techAnim.length > 0) {
      $doc = $(document);
      window.techAnim = new techAnimation();
      $container = $('.slides');
      return $container.fullpage({
        verticalCentered: false,
        css3: true,
        navigation: true,
        navigationPosition: 'left',
        navigationTooltips: ['', 'Infrastructure', 'Gateway', 'Load Balancing', 'Application', 'Bastion', 'Database', 'Scale'],
        showActiveTooltip: true,
        afterLoad: function(anchorLink, index) {
          return techAnim.play[index - 1].call(this);
        },
        onLeave: function(index, nextIndex, direction) {
          techAnim.stopIntro();
          return techAnim.leave[index - 1].call(this);
        },
        afterRender: function() {
          return $container.css('opacity', 1);
        }
      });
    }
  });

  techAnimation = (function() {
    var infrastructure, intro, leaveApp, leaveBastion, leaveDatabase, leaveGateway, leaveInfrastructure, leaveIntro, leaveNetwork, leaveScaling, network, playApp, playBastion, playDatabase, playGateway, playIntro, playNetwork, playScaling;

    function techAnimation() {}

    network = null;

    intro = {
      visible: false,
      state: false,
      play: false,
      leave: false,
      end: false
    };

    infrastructure = {
      play: false
    };

    playIntro = function() {
      animate({
        el: '.console',
        easing: 'easeOutCirc',
        opacity: [0, 1],
        translateY: [1000, 0],
        duration: 1500,
        delay: 100
      });
      animate({
        el: '.intro-header',
        easing: 'easeOutCirc',
        opacity: [0, 1],
        duration: 1500,
        delay: 1600
      });
      animate({
        el: '.intro-text',
        easing: 'easeOutQuad',
        opacity: [0, 1],
        duration: 1500,
        delay: 1900
      });
      animate({
        el: '.primary-header',
        easing: 'easeOutQuad',
        opacity: [0, 1],
        duration: 1000,
        delay: 2300
      });
      return setTimeout((function() {
        var $src;
        $src = $('.b1-text');
        return Helpers.typeConsole('aptible apps:create test-app', $src);
      }), 2000);
    };

    playGateway = function() {
      $('.http, .ssh').addClass('faded');
      setTimeout((function() {
        return $('.docker').addClass('faded');
      }), 100);
      network = new Network();
      network.generateNetwork();
      return network.generateLines();
    };

    playNetwork = function() {
      return $('.http, .load-balancer').removeClass('faded');
    };

    playApp = function() {
      return $('.app').removeClass('faded');
    };

    playBastion = function() {
      return $('.ssh, .bastion').removeClass('faded');
    };

    playDatabase = function() {
      return $('.database').removeClass('faded');
    };

    playScaling = function() {
      $('.load-balancer, .app, .bastion').removeClass('faded');
      return setTimeout((function() {
        return network.runHalf2();
      }), 3000);
    };

    techAnimation.prototype.stopIntro = function() {
      return animate.stop('.console');
    };

    leaveIntro = function() {
      if (!intro.leave) {
        return animate({
          el: '.console',
          easing: 'easeOutQuad',
          translateY: [0, 50],
          opacity: [1, 0],
          duration: 400,
          begin: function() {
            return intro.leave = true;
          }
        });
      }
    };

    leaveInfrastructure = function() {
      return $('#infrastructure .copy').fadeOut(150);
    };

    leaveGateway = function() {
      $('#gateway .copy').fadeOut(150);
      return network.runHttp();
    };

    leaveNetwork = function() {
      $('#network .copy').fadeOut(150);
      $('.http, .load-balancer').addClass('faded');
      return network.stop();
    };

    leaveApp = function() {
      $('#code .copy').fadeOut(150);
      $('.app').addClass('faded');
      return network.runSSH();
    };

    leaveBastion = function() {
      $('#bastion .copy').fadeOut(150);
      $('.bastion').addClass('faded');
      $('.ssh').addClass('faded');
      return network.stop();
    };

    leaveDatabase = function() {
      $('#database .copy').fadeOut(150);
      return network.runHalf();
    };

    leaveScaling = function() {};

    techAnimation.prototype.play = [playIntro, animInfrastructure, playGateway, playNetwork, playApp, playBastion, playDatabase, playScaling];

    techAnimation.prototype.leave = [leaveIntro, leaveInfrastructure, leaveGateway, leaveNetwork, leaveApp, leaveBastion, leaveDatabase, leaveScaling];

    return techAnimation;

  })();

}).call(this);
